version: 2.1
jobs:
  compile:
   docker:
      - image: vcyzteen/bakaburn:latest
   steps:
      - run:
          command: |
            apt-get -y update && apt-get -y upgrade && apt-get -y install ca-certificates
      - run:
          command: |
            bash setup
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
